import '../services/language_service.dart';

class AppTexts {
  static final String _currentLang = LanguageService.getSystemLanguage();

  static final Map<String, Map<String, String>> _localizedValues = {
    'es': {
      'login_welcome': '¡Hola! Soy Lumi. ¡Introduce tus datos para empezar!',
      'login_offline_star': '¡Uy! No veo internet...',
      'btn_guest': 'ENTRAR COMO INVITADO',
      'offline_title': '¡Uy! No hay internet ☁️',
      'offline_body':
          '¡Ups! No tienes internet. ¿Quieres probar otra vez o entrar como invitado?',
      'btn_retry': 'REINTENTAR',
      'new_user': '¿Eres nuevo? ¡Regístrate aquí!',
      'create_account': 'Crear cuenta',
      'forgot_password': '¿Olvidaste tu contraseña?',
      'login_error': '¡Ups! Revisa que los datos sean correctos.',
      'loading': 'Cargando...',
      'session': 'Iniciando sesión',
      'password': 'Contraseña',
      'no_valid_pass': 'Contraseña no válida.',
      'no_valid_user': 'Usuario no válido.',
      'username': 'Nombre de usuario',
      'mode_offline': 'Modo offline ☁️',
      'no_conection_to_school':
          'No hemos podido conectar con la escuela. ¿Quieres entrar para jugar un rato? (Tus avances no se guardarán en la nube).',
      'perfect_enter': '¡Genial! Entrando...',
      'have_account': '¿Ya tienes cuenta?',
      'boy': 'Niño',
      'girl': 'Niña',
      'who_you_are': '¿Quién eres?',
      'repite_pass': 'Repite tu contraseña',
      'you_secret_key': 'Tu clave secreta ',
      'your_name': '¿Cómo te llamas?',
      'create_your_account': '¡Crea tu cuenta!',
      'start_adventure': '¡Empezar la aventura!',
      'profile': 'Perfil',
      'syllabus': 'Temario',
      'science': 'Ciencias',
      'lenguage': 'Lengua',
      'math': 'Matemáticas',
      'english': 'Inglés',
      'explore_syllabus': '¡Explora el temario!',
      'continue': 'Continuando...',
      'continue_learning': '¡Continuar aprendiendo!',
      'hello_what_want_learn': '¡Hola! ¿Qué quieres aprender hoy?',
      'ready_discover_something_new': '¿Listo para descubrir algo nuevo hoy?',
      'explore_syllabus_continue':
          '¡Explora el temario y continúa tu aventura!',
      'exit': 'Salir',
      'help': 'Ayuda',
      'warning': 'Avisos',
      'progress': 'Progreso',
      'my_achievements': 'Mis logros',
      'stay': 'QUEDARME',
      'your_adventure_waits':
          '¡Tu aventura te esperará aquí mismo hasta que vuelvas!',
      'are_you_leaving': '¿Ya te vas?',
      'welcome': '¡Bienvenido a Escuela Valiente!',
      'lulu_intro': 'Soy Lumi, tu ayudante virtual.',
      'ready_learn': '¿Estamos listos para aprender?.',
      'login_prompt': 'Inicia sesión para continuar',
      'home': 'Inicio',
      'loading_adventure': 'Cargando aventura...',
      'error_name_exists': '¡Ups! El nombre de usuario ya existe. Por favor, elige otro.',
      'error_weak_pass': '¡Ups! La contraseña es demasiado débil. Por favor, elige una contraseña más segura.',
    },
    'en': {
      'login_welcome': 'Hi! I am Lumi. Enter your details to start!',
      'login_offline_star': 'Oops! I don\'t see any internet...',
      'btn_guest': 'ENTER AS GUEST',
      'offline_title': 'Oops! No internet ☁️',
      'offline_body':
          'It seems your connection went for a walk. Do you want to try again or enter as a guest?',
      'btn_retry': 'RETRY',
      'new_user': 'New here? Sign up now!',
      'create_account': 'Create Account',
      'forgot_password': 'Forgot your password?',
      'login_error': 'Oops! Please check your details and try again.',
      'loading': 'Loading...',
      'session': 'Starting session',
      'password': 'Password',
      'no_valid_pass': 'Invalid password.',
      'no_valid_user': 'Invalid username.',
      'username': 'Username',
      'mode_offline': 'Offline mode ☁️',
      'no_conection_to_school':
          'We couldn\'t connect to the school. Do you want to enter to play for a while? (Your progress won\'t be saved in the cloud).',
      'perfect_enter': 'Great! Entering...',
      'have_account': 'Already have an account?',
      'boy': 'Boy',
      'girl': 'Girl',
      'who_you_are': 'Who are you?',
      'repite_pass': 'Repeat your password',
      'you_secret_key': 'Your secret key',
      'your_name': 'What\'s your name?',
      'create_your_account': 'Create your account!',
      'start_adventure': 'Start the adventure!',
      'profile': 'Profile',
      'syllabus': 'Syllabus',
      'science': 'Science',
      'lenguage': 'Language',
      'math': 'Math',
      'english': 'English',
      'explore_syllabus': 'Explore the syllabus!',
      'continue': 'Continuing...',
      'continue_learning': 'Keep learning!',
      'hello_what_want_learn': 'Hi! What do you want to learn today?',
      'ready_discover_something_new': 'Ready to discover something new today?',
      'explore_syllabus_continue':
          'Explore the syllabus and continue your adventure!',
      'exit': 'Exit',
      'help': 'Help',
      'warning': 'Warnings',
      'progress': 'Progress',
      'my_achievements': 'My achievements',
      'stay': 'STAY',
      'your_adventure_waits':
          'Your adventure will be waiting right here for you until you return!',
      'are_you_leaving': 'Are you leaving already?',
      'welcome': 'Welcome to Brave School!',
      'lulu_intro': 'I\'m Lulu, your virtual helper.',
      'ready_learn': 'Are we ready to learn?.',
      'login_prompt': 'Log in to continue',
      'home': 'Home',
      'loading_adventure': 'Loading adventure...',
      'error_name_exists': 'Oops! Username already exists. Please choose another one.',
      'error_weak_pass': 'Oops! The password is too weak. Please choose a stronger password.',
    },
    'ca': {
      'login_welcome': 'Hola! Soc la Lumi. Introdueix les dades per començar!',
      'login_offline_star': 'Ui! No veig internet...',
      'btn_guest': 'ENTRA COM A CONVIDAT',
      'offline_title': 'Ui! No hi ha internet ☁️',
      'offline_body':
          'Sembla que la teva connexió ha anat a fer un volt. Vols tornar-ho a provar o entrar com a convidat?',
      'btn_retry': 'REINTENTAR',
      'new_user': 'Ets nou? Registra\'t aquí!',
      'create_account': 'Crear compte',
      'forgot_password': 'Has oblidat la teva contrasenya?',
      'login_error': 'Ups! Revisa que les dades siguin correctes.',
      'loading': 'Carregant...',
      'session': 'Iniciant sessió',
      'password': 'Contrasenya',
      'no_valid_pass': 'Contrasenya no válida.',
      'no_valid_user': 'Usuari no válido.',
      'username': 'Nom d\'usuari',
      'mode_offline': 'Mode offline ☁️',
      'no_conection_to_school':
          'No hem pogut connectar amb l\'escola. Vols entrar per jugar una estona? (Els teus avanços no es guardaran al núvol).',
      'perfect_enter': 'Genial! Entrant...',
      'have_account': 'Ja tens compte?',
      'boy': 'Nen',
      'girl': 'Nena',
      'who_you_are': 'Qui ets?',
      'repite_pass': 'Repeteix la teva contrasenya',
      'you_secret_key': 'La teva clau secreta',
      'your_name': 'Com et dius?',
      'create_your_account': 'Crea el teu compte!',
      'start_adventure': 'Comença l\'aventura!',
      'profile': 'Perfil',
      'syllabus': 'Temari',
      'science': 'Ciències',
      'lenguage': 'Llengua',
      'math': 'Matemàtiques',
      'english': 'Anglès',
      'explore_syllabus': 'Explora el temari!',
      'continue': 'Continuando...',
      'continue_learning': 'Continua aprenent!',
      'hello_what_want_learn': 'Hola! Què vols aprendre avui?',
      'ready_discover_something_new': 'Preparat per descubrir algo nou?',
      'explore_syllabus_continue':
          'Explora el temari i continua l\'aventura!',
      'exit': 'Surt',
      'help': 'Ajuda',
      'warning': 'Avisos',
      'progress': 'Progrés',
      'my_achievements': 'Els meus èxits',
      'stay': 'QUEDARME',
      'your_adventure_waits':
          'La teva aventura t\'esperarà aquí mateix fins que tornis!',
      'are_you_leaving': 'Ja te\'n vas?',
      'welcome': 'Benvingut a l\'Escola Valenta!',
      'lulu_intro': 'Sóc la Lumi, la teva ajudant virtual.',
      'ready_learn': 'Estem preparats per aprendre?.',
      'login_prompt': 'Inicia sessió per continuar',
      'home': 'Inici',
      'loading_adventure': 'Carregant aventura...',
      'error_name_exists': 'Ups! El nom d\'usuari ja existeix. Por favor, elige otro.',
      'error_weak_pass': 'Ups! La contrasenya es demasiado débil. Por favor, elige una contraseña más segura.',

    },
  };

  static String getText(String key) {
    return _localizedValues[_currentLang]?[key] ??
        _localizedValues['es']![key] ??
        'Text missing';
  }
}
