// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1vs73u0YteeY6M3RPLH5ceps8TfqVXHI',
    appId: '1:804785573757:web:807618fec052047dc94614',
    messagingSenderId: '804785573757',
    projectId: 'escuela-valiente-tfg',
    authDomain: 'escuela-valiente-tfg.firebaseapp.com',
    storageBucket: 'escuela-valiente-tfg.firebasestorage.app',
    measurementId: 'G-L6X4RRDK5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSR7qM8c3N4SCR0Jhdv5LRdvB_W5XQkTA',
    appId: '1:804785573757:android:3a526ce6cdfa0ef0c94614',
    messagingSenderId: '804785573757',
    projectId: 'escuela-valiente-tfg',
    storageBucket: 'escuela-valiente-tfg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRBU5_uUQfgvh0DoyaRF0M6RCOu1e_gcM',
    appId: '1:804785573757:ios:b24934776d0e9f2cc94614',
    messagingSenderId: '804785573757',
    projectId: 'escuela-valiente-tfg',
    storageBucket: 'escuela-valiente-tfg.firebasestorage.app',
    iosBundleId: 'com.marcmarzaosa.escuelavaliente',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRBU5_uUQfgvh0DoyaRF0M6RCOu1e_gcM',
    appId: '1:804785573757:ios:83908db1acd7597ec94614',
    messagingSenderId: '804785573757',
    projectId: 'escuela-valiente-tfg',
    storageBucket: 'escuela-valiente-tfg.firebasestorage.app',
    iosBundleId: 'com.example.escuelaValienteTfg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1vs73u0YteeY6M3RPLH5ceps8TfqVXHI',
    appId: '1:804785573757:web:cc1195dd377eadeac94614',
    messagingSenderId: '804785573757',
    projectId: 'escuela-valiente-tfg',
    authDomain: 'escuela-valiente-tfg.firebaseapp.com',
    storageBucket: 'escuela-valiente-tfg.firebasestorage.app',
    measurementId: 'G-GHMZD3QJRT',
  );
}
